import builder from "./builder"
import "./models/User"
import "./models/Test"
import "./models/Chapter"
import "./models/EnrollHistory"
import "./models/Question"
import "./models/Rating"
import "./models/TestHistory"
import "./Query"
import "./Mutation"
export default builder
